Definition of Layout and Routing
rasengan-dev/rasenganjs-examples pull request #9
Opened 2024-07-16 19:34 UTC by dilane3

What is done:

- Routing ✅
- Dashboard Layout (only for desktop) ✅
- Input Component ✅
- Sidebar Button Component ✅
- Card Container, to show elements ✅
- Typography Component ✅
- Divider Component ✅

2024-07-16 19:51 UTC, konnofuente commented on templates/dashboard/model1/src/app/root/pages/ui/atoms.page.tsx
Is better if we avoid using svg code directly in our cde base

2024-07-16 20:04 UTC, konnofuente requested changes
You did great all i can request is to 
-avoid using hardcoded svg that will be all n my side 

thanks

2024-07-16 20:51 UTC, dilane3 commented on templates/dashboard/model1/src/app/root/pages/ui/atoms.page.tsx
Resolved

2024-07-16 23:18 UTC, jeansamist commented
I think it's not integrated exactly as on the model. I will create good consistency between the model and the theme

2024-07-17 08:24 UTC, konnofuente approved these changes

2024-07-17 08:27 UTC, merged